import test from 'node:test';
import assert from 'node:assert/strict';
import { learningIdentity } from '../src/skills/identity.ts';
import { skillEligibility } from '../src/skills/context.ts';
const content={type:'review_procedure',scopeType:'review_method',title:'Check empty candidate inputs',conditions:['When ranking changes'],steps:['Inspect callers','Compare empty input behavior'],counterexamples:['Caller rejects empty inputs'],stopConditions:['Contract established'],paths:['font.py'],languages:['Python'],keywords:['empty'],symbols:['score'],dependencies:[]};
const input=()=>({policy:'test',source:{id:'run:real-uuid',runId:'real-uuid',repositoryKey:'repo:a'},report:{status:'completed'},sourcePages:[{path:'font.py',fileHash:'a'.repeat(64),lines:['code']}],toolEvents:[],relevantSkills:[{...content,id:'sk_old',owner:'learner',revision:2,repositoryKey:'repo:a',state:'trial',sources:[]}],fixedRules:'rules',bankSnapshotId:'b'.repeat(64)});
const output=x=>({operations:[{op:'add',targetRef:x.visible.newTargets[0],sourceRefs:[x.visible.source.ref],reason:'Current source supports this method',content:{...content,dependencies:undefined,dependencyRefs:[x.visible.sourcePages[0].ref]}}]});
function valid(x){const o=output(x);delete o.operations[0].content.dependencies;return o;}
test('opaque identity valid refs bind real source, revision and dependency without model hashes',()=>{const x=learningIdentity(input()),o=valid(x),r=x.resolve(o).operations[0];assert.deepEqual(r.sourceIds,['run:real-uuid']);assert.deepEqual(r.content.dependencies,[{path:'font.py',hash:'a'.repeat(64)}]);assert.doesNotMatch(JSON.stringify(x.visible),/real-uuid|aaaaaaaaaaaaaaaa|bbbbbbbbbbbbbbbb/);o.operations[0].op='revise';o.operations[0].targetRef=x.visible.relevantSkills[0].ref;assert.equal(x.resolve(o).operations[0].expectedRevision,2);});
test('opaque unknown refs fail closed',()=>{const x=learningIdentity(input()),o=valid(x);o.operations[0].content.dependencyRefs=['evidence_unknown'];assert.throws(()=>x.resolve(o),/Unknown/);});
test('opaque duplicate refs and target operations fail closed',()=>{const x=learningIdentity(input()),o=valid(x);o.operations[0].sourceRefs.push(x.visible.source.ref);assert.throws(()=>x.resolve(o),/duplicate/);const p=valid(x);p.operations.push(p.operations[0]);assert.throws(()=>x.resolve(p),/Duplicate/);const q=valid(x);q.operations[0].content.dependencyRefs.push(q.operations[0].content.dependencyRefs[0]);assert.throws(()=>x.resolve(q),/Duplicate/);});
test('opaque cross-input refs cannot be replayed',()=>{const a=learningIdentity(input()),b=learningIdentity({...input(),bankSnapshotId:'c'.repeat(64)});assert.throws(()=>b.resolve(valid(a)),/Unknown/);});
test('opaque stale revision ref fails binding verification',()=>{const i=input(),x=learningIdentity(i);i.relevantSkills[0].revision++;assert.throws(()=>x.resolve(valid(x),i),/stale revision/);});
test('opaque host hash mismatch and raw hash bypass fail closed',()=>{const i=input(),x=learningIdentity(i);i.sourcePages[0].fileHash='c'.repeat(64);assert.throws(()=>x.resolve(valid(x),i),/host hash mismatch/);const y=learningIdentity(input()),o=valid(y);o.operations[0].content.dependencies=[{path:'font.py',hash:'a'.repeat(64)}];assert.throws(()=>y.resolve(o),/raw dependency/);const p=valid(y);p.operations[0].expectedRevision=2;assert.throws(()=>y.resolve(p),/raw identity/);});
test('review methods match other paths only inside repository and language; facts retain strict path',()=>{const s={...content,state:'trial',repositoryKey:'repo:a'};assert.equal(skillEligibility(s,'repo:a',['widget.py'],'empty candidate score').eligible,true);assert.equal(skillEligibility(s,'repo:b',['widget.py'],'empty').eligible,false);assert.equal(skillEligibility(s,'repo:a',['widget.js'],'empty').eligible,false);assert.equal(skillEligibility({...s,scopeType:'repository_fact'},'repo:a',['widget.py'],'empty').eligible,false);assert.equal(skillEligibility({...s,scopeType:undefined},'repo:a',['widget.py'],'empty').eligible,false);assert.equal(skillEligibility(s,'repo:a',['widget.py'],'unrelated').softCues.strength,'weak');assert.equal(skillEligibility({...s,state:'retired'},'repo:a',['font.py'],'empty').eligible,false);});
